name: Build Wget

on:
  push:
    branches:
      - ino_dev

jobs:
  build:
    name: Build and Upload Wget
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
          RUN apt update && apt install -y \
          build-essential \
          autoconf \
          automake \
          autopoint \
          texinfo \
          flex \
          gperf \
          gettext \
          libssl-dev \
          libgnutls28-dev \
          zlib1g-dev \
          pkg-config \
          git \
          wget \
          autoconf-archive \
          ca-certificates \
          checkinstall

      - name: Run bootstrap script
        run: ./bootstrap

      - name: Configure the build
        run: ./configure --with-ssl=openssl

      - name: Build wget
        run: make -j$(nproc)

      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: wget-binary
          path: src/wget
